---
# build "straat" zal hier nog moeten verdwijnen.
version: "3"

services:
  dind:
    image: opvolger/dind:latest
    privileged: true
    container_name: dind
    ports:
      - "10022:22"
    networks:
      default:
        aliases:
          - dind
    environment:
      USER: dind
      PASSWORD: dind
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      JAVA_OPTS: -Dhudson.footerURL=http://opvolger.eu
