---
- hosts: dummy
  gather_facts: false
  tasks:
    - block:
        - name: Add folder in jenkins
          jenkins_script:
            script: "{{ lookup('template', 'templates/add_folder.groovy') }}"
            user: "{{ jenkins.username }}"
            password: "{{ jenkins.password }}"
            url: "{{ jenkins.url }}"
          vars:
            folder: INFRA
          register: jenkins_script_out
          changed_when: '"exists" not in jenkins_script_out.output'

        - name: Create a jenkins job using basic authentication
          jenkins_job:
            config: "{{ lookup('template', 'templates/jenkins_job_docker_pxe.xml') }}"
            name: "INFRA/Build_docker_image_opvolger-pxe"
            user: "{{ jenkins.username }}"
            password: "{{ jenkins.password }}"
            url: "{{ jenkins.url }}"

        - name: Secret voor dockerhub
          jenkins_script:
            script: "{{ lookup('template', 'templates/add_creds_username_password.groovy') }}"
            user: "{{ jenkins.username }}"
            password: "{{ jenkins.password }}"
            url: "{{ jenkins.url }}"
          vars:
            username: "{{ docker_hub_username }}"
            secret: "{{ docker_hub_token }}"
            id: "dockerhub"
            description: "Creds for docker-hub"
          register: jenkins_script_out
          changed_when: '"no password" not in jenkins_script_out.output'
      delegate_to: localhost
