- hosts: dummy
  gather_facts: false
  tasks:
    - block:
        - name: Setup Jenkins
          jenkins_script:
            script: "{{ lookup('template', 'templates/setup_admin.groovy') }}"
            user: "{{ jenkins.username }}"
            password: "{{ jenkins.password }}"
            url: "{{ jenkins.url }}"

        - name: Secret slaves
          jenkins_script:
            script: "{{ lookup('template', 'templates/add_creds_username_password.groovy') }}"
            user: "{{ jenkins.username }}"
            password: "{{ jenkins.password }}"
            url: "{{ jenkins.url }}"
          vars:
            username: "{{ slave.username }}"
            secret: "{{ slave.password }}"
            id: "ssh_creds_{{ slave.hostname }}"
            description: "Creds for slave {{ slave.hostname }}"
          loop: "{{ jenkins.slaves|flatten(levels=1) }}"
          loop_control:
            loop_var: slave

        - name: Create slaves
          jenkins_script:
            script: "{{ lookup('template', 'templates/add_slave.groovy') }}"
            user: "{{ jenkins.username }}"
            password: "{{ jenkins.password }}"
            url: "{{ jenkins.url }}"

      delegate_to: localhost
