- hosts: dummy
  gather_facts: false
  tasks:
    - block:
        - name: Setup Jenkins
          jenkins_script:
            script: "{{ lookup('template', 'templates/setup_admin.groovy') }}"
            user: "{{ jenkins.username }}"
            password: "{{ jenkins.password }}"
            url: "{{ jenkins.url }}"
          register: jenkins_script_out
          changed_when: '"creating local admin-user" in jenkins_script_out.output'

        - name: Secret slaves
          jenkins_script:
            script: "{{ lookup('template', 'templates/add_creds_username_password.groovy') }}"
            user: "{{ jenkins.username }}"
            password: "{{ jenkins.password }}"
            url: "{{ jenkins.url }}"
          vars:
            username: "{{ slave.username }}"
            secret: "{{ slave.password }}"
            id: "ssh_creds_{{ slave.hostname }}"
            description: "Creds for slave {{ slave.hostname }}"
          loop: "{{ jenkins.slaves }}"
          loop_control:
            loop_var: slave
          register: jenkins_script_out
          no_log: true
          changed_when: '"no password changed" not in jenkins_script_out.output'

        - name: Create slaves
          jenkins_script:
            script: "{{ lookup('template', 'templates/add_slave.groovy') }}"
            user: "{{ jenkins.username }}"
            password: "{{ jenkins.password }}"
            url: "{{ jenkins.url }}"
          register: jenkins_script_out
          no_log: true
          changed_when: '"slave docker found" not in jenkins_script_out.output'

      delegate_to: localhost
