- hosts: dummy
  gather_facts: false
  tasks:
    - block:
        - name: Add folder in jenkins
          jenkins_script:
            script: |
              import com.cloudbees.hudson.plugins.folder.*
              import org.jenkinsci.plugins.workflow.job.WorkflowJob
              import jenkins.model.Jenkins

              Jenkins jenkins = Jenkins.instance // saves some typing

              // Bring some values in from ansible using the jenkins_script modules wierd "args" approach (these are not gstrings)
              String folderName = "INFRA"

              def folder = jenkins.getItem(folderName)
              if (folder == null) {
                // Create the folder if it doesn't exist or if no existing job has the same name
                folder = jenkins.createProject(Folder.class, folderName)
                println "created folder ${folderName}"
              }else{
                println "folder ${folderName} exists"
              }
            user: "{{ jenkins.username }}"
            password: "{{ jenkins.password }}"
            url: "{{ jenkins.url }}"

        - name: Create a jenkins job using basic authentication
          community.general.jenkins_job:
            config: "{{ lookup('template', 'templates/jenkins_job_docker_pxe.xml') }}"
            name: "INFRA/Build_docker_image_opvolger-pxe"
            user: "{{ jenkins.username }}"
            password: "{{ jenkins.password }}"
            url: "{{ jenkins.url }}"

        - name: Secret slaves
          jenkins_script:
            script: "{{ lookup('template', 'templates/add_creds_username_password.groovy') }}"
            user: "{{ jenkins.username }}"
            password: "{{ jenkins.password }}"
            url: "{{ jenkins.url }}"
          vars:
            username: "{{ slave.username }}"
            secret: "{{ slave.password }}"
            id: "ssh_creds_{{ slave.hostname }}"
            description: "Creds for slave {{ slave.hostname }}"
          loop: "{{ jenkins.slaves|flatten(levels=1) }}"
          loop_control:
            loop_var: slave

        - name: Create slaves
          jenkins_script:
            script: "{{ lookup('template', 'templates/add_slave.groovy') }}"
            user: "{{ jenkins.username }}"
            password: "{{ jenkins.password }}"
            url: "{{ jenkins.url }}"

        - name: Secret voor dockerhub
          jenkins_script:
            script: "{{ lookup('template', 'templates/add_creds_username_password.groovy') }}"
            user: "{{ jenkins.username }}"
            password: "{{ jenkins.password }}"
            url: "{{ jenkins.url }}"
          vars:
            username: "{{ docker_hub_username }}"
            secret: "{{ docker_hub_token }}"
            id: "dockerhub"
            description: "Creds for docker-hub"
      delegate_to: localhost
