- hosts: deploy
  tasks:
    - name: Create dir for docker-compose file
      file:
        path: "{{ docker_deploy.dir }}"
        state: directory

    - name: Create dir for volume_pxe
      file:
        path: "{{ docker_deploy.volume_pxe }}"
        state: directory

    - name: copy docker-compose file
      copy:
        src: '../generated/docker-compose.yaml'
        dest: "{{ docker_deploy.dir }}"

    - name: copy volume_pxe file
      copy:
        src: '../generated/pxe/'
        dest: "{{ docker_deploy.volume_pxe }}"

