---
- import_playbook: playbook_create_wimboot_files.yaml
  when: wimboot.generate | bool

- hosts: dummy
  gather_facts: false
  tasks:
    - set_fact:
        dir_generated: "{{ playbook_dir }}/../generated"

    - name: Generate files
      block:
        - name: Crete docker-compose.yaml
          template: 
            src: docker-compose.yaml
            dest: '{{ dir_generated }}'

        - name: create dir images
          file:
            path: "{{ dir_generated }}/pxe/ipxe"
            state: directory

        - name: get dir without 'appears to use backslashes as path separators'
          shell: pwd
          args:
            chdir: '{{ dir_generated }}'
          register: pwd

        - name: Unarchive a file that needs to be downloaded (added in 2.0)
          unarchive:
            src: '{{ pwd.stdout_lines[0] }}/winpe.zip'
            dest: '{{ pwd.stdout_lines[0] }}'
            remote_src: yes

        - include_tasks: tasks/generate_windows_files.yaml
          when: boot_ipxe.menu_os_items['windows'] is defined

        - name: Create boot.ipxe
          template: 
            src: boot.ipxe
            dest: '{{ dir_generated }}/pxe/ipxe'

        - name: create dir images
          file:
            path: "{{ dir_generated }}/pxe/images"
            state: directory

        - name: download image
          get_url:
            url: "{{ boot_ipxe.download_png }}"
            dest: '{{ dir_generated }}/pxe/images/splash.png'

      delegate_to: localhost

