---
# create wimboot
# This windows machine must gave installed Windows ADK and Windows PE add-on for the ADK!!!
# https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install
# enable winrm on Windows machine `Enable-PSRemoting -Force`
- hosts: windows_adk
  gather_facts: true
  tasks:
    - name: generate wimboot
      block:
        - set_fact:
            dir_temp: "c:\\temp"
            dir_generated: "{{ playbook_dir }}/../generated"
            dir_download: "{{ playbook_dir }}/../download"

        - name: create temp dir
          win_file:
            path: "{{ dir_temp }}"
            state: directory

        - name: download image
          get_url:
            url: "{{ wimboot.background_jpg }}"
            dest: "{{ dir_download }}/winpe.jpg"
          delegate_to: localhost

        - name: copy scripts
          win_copy:
            src: "{{ item }}"
            dest: '{{ dir_temp }}\{{ item | basename }}'
          with_items:
            - "{{ dir_download }}/winpe.jpg"
            - set_adk_vars_and_run_powershell_script.bat
            - create_winpe_with_powershell.ps1

        - name: run scripts (can take some time)
          win_shell: cmd.exe /c c:\temp\set_adk_vars_and_run_powershell_script.bat

        # https://superuser.com/questions/1369344/zip-file-made-in-powershell-cant-be-used-in-linux
        - name: zip a directory
          win_command: "\"C:\\Program Files\\7-Zip\\7z.exe\" a -tzip -o{{ dir_temp }} winpe.zip {{ dir_temp }}\\winpe"
          #win_shell: 'Compress-Archive -Path {{ dir_temp }}\\winpe -DestinationPath {{ dir_temp }}\\winpe.zip'
          args:
            chdir: "{{ dir_temp }}"

        - name: "Download with samba"
          block:
            - name: Check if samba-client is installed
              shell: smbclient --version
              register: shell_out

            - name: Fail is samba-client is not installed
              fail:
                msg: "aborting, samba-client isn't installed. Install it with your favorite package manager"
              when: '"Version" not in shell_out.stdout'

            - name: "copy release FRB from samba-share"
              command: 'smbclient ''\\{{ inventory_hostname }}\c$'' -U ''{{ ansible_user }}''%{{ ansible_password }} -c ''prompt OFF; recurse ON; cd "temp"; lcd {{ playbook_dir }}/../generated/; mget winpe.zip'''
              register: release_downloaded
              no_log: True # your creds!
          delegate_to: localhost
          when: wimboot.download_with_samba | bool

        - name: get zip (very slow 30m+ big file and winrm!)
          fetch:
            src: "{{ dir_temp }}\\winpe.zip"
            dest: "{{ dir_generated }}/pxe/winpe.zip"
            flat: yes
          when: not wimboot.download_with_samba | bool
