---
- import_playbook: playbook_create_wimboot_files.yaml
  when: wimboot.generate | bool

- import_playbook: playbook_create_linux_boot_files.yaml

- hosts: deploy
  gather_facts: false
  tasks:
    - set_fact:
        dir_generated: "{{ playbook_dir }}/../generated"

    - name: Generate files
      block:
        - name: Crete docker-compose.yaml
          template:
            src: docker-compose.yaml
            dest: "{{ dir_generated }}"

        - name: create dir images
          file:
            path: "{{ dir_generated }}/pxe/ipxe"
            state: directory

        - import_tasks: tasks/generate_windows_files.yaml
          when: boot_ipxe.menu_os_items['windows'] is defined

        - name: Create boot.ipxe
          template:
            src: boot.ipxe
            dest: "{{ dir_generated }}/pxe/ipxe"

        - name: create dir images
          file:
            path: "{{ dir_generated }}/pxe/images"
            state: directory

        - name: download image
          get_url:
            url: "{{ boot_ipxe.background_png }}"
            dest: "{{ dir_generated }}/pxe/images/splash.png"

      delegate_to: localhost
