---
- import_playbook: playbook_create_wimboot_files.yaml
  when: wimboot.generate | bool

- hosts: deploy
  gather_facts: false  
  tasks:
    - set_fact:
        dir_generated: "{{ playbook_dir }}/../generated"
        dir_download: "{{ playbook_dir }}/../download"

    - name: Get boot files from iso
      include_tasks: tasks/get_linux_iso_files.yaml
      with_items: "{{ boot_ipxe.menu_os_items['linux'] }}"
      loop_control:
        loop_var: linux_item
      when: boot_ipxe.menu_os_items['linux'] is defined
