---
- import_playbook: playbook_deploy_files.yaml

- hosts: deploy
  tasks:
    - name: docker compose down (maybe it is stil on?)
      shell: docker compose down
      args:
        chdir: "{{ docker_deploy.dir }}"

    - name: pull opvolger/pxe:latest image
      shell: docker pull opvolger/pxe:latest
      args:
        chdir: "{{ docker_deploy.dir }}"

    - name: docker compose up -d (start)
      shell: docker compose up -d
      args:
        chdir: "{{ docker_deploy.dir }}"
